# CI configuration for movim
# Author: Sai Karthik < kskarthik@disroot.org >

name: Movim CI

on:
  push:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build-with-mariadb:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install movim dependencies
      run: composer install --prefer-dist --no-progress


    - name: Setup .env file
      run: |
      cp .env.example .env
      sed -i \
      -e 's/^DB_DRIVER=.*/DB_DRIVER=mysqli/' \
      -e 's/^DB_PORT=.*/DB_PORT=3306/' \
      .env

    - name: Setup mariadb
      uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: "mariadb"
        mysql-version: "11.7.2"
        user: movim
        password: movim

  build-with-postgres:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install movim dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup .env file
      run: cp .env.example .env

    - name: Setup Postgres database
      uses: Daniel-Marynicz/postgresql-action@master
      with:
       postgres_image_tag: 17-alpine
       app_user: movim
       app_user_password: movim
       app_db: movim
       postgres_extensions: pgcrypto

    - name: Perform database migration using composer
      run: composer movim:migrate

    - name: Perform database rollback
      run: php vendor/bin/phinx rollback -t 20180314212906

    - name: ...and migrate again
      run: composer movim:migrate

    - name: Start movim daemon
      run: php daemon.php start &
